config/routes.rb
Rails.application.routes.draw do
  
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :products, only: [:index]

  root 'main#index'
  post '/sendtest' => 'tm#sendtest'
  post '/send' => 'tm#trigger_sms_alerts'
  
  get '/admin' => 'admin#panel'
  get '/admin/prev_list' => 'admin#prev_list'
  get '/admin/session_list' => 'admin#session_list'     
  get '/admin/admin_list' => 'admin#admin_list'
  get '/admin/register' => 'admin#register'
  get '/admin/publicity' => 'admin#publicity'
  get '/admin/publicity_new' => 'admin#publicity_new'
  get '/admin/publicity/history' => 'admin#publicity_history'
  get '/admin/admin_enrollment' => 'admin#admin_enrollment'
  post '/admin/admin_enrollment/create' => 'admin#admin_enrollment_create'
  post '/admin/create' => 'admin#create'
  post '/admin/delete' => 'admin#delete'
  post '/admin/publicity_new/sendtext' => 'admin#sendtext_user'
  get '/admin/video' => 'admin#video'
  post '/admin/video/create' => 'admin#video_create'
  get '/admin/news' => 'admin@news'
  post '/admin/news/create' => 'admin#news_create'
  post '/admin/statistics/member/record' => 'admin#statistics_member_record'
  
  get '/video/index' => 'video#index'
  get '/video/player' => 'video#player'
  post '/video/comment' => 'video#comment'
  get '/news/index' => 'news#newsindex'
  get '/news/article' => 'news#article'
  get '/blog/index' => 'news#blogindex'
  post '/news/comment' => 'news#comment'
  get '/users/invitation' => 'users#invitation'
  post '/users/invitation/sendtext' => 'users#invitation_sendtext'
  
  get '/error' => 'sessions#error'
  
  get '/admin/statistics/member' => 'admin#statistics_member'
  get '/admin/statistics/post' => 'admin#statistics_post'
  
  resources :videos, except: [:show] do
    post "/like", to: "video#like_toggle"
  end
  resources :news, except: [:show] do
    post "/like", to: "news#like_toggle"
  end

end

app/models/video.rb
class Video < ActiveRecord::Base
    is_impressionable
    
    has_many :likevideos
    has_many :liked_users, through: :likevideos, source: :user
    has_many :commentvideos
end

app/controllers/video_controller.rb
class VideoController < ApplicationController
    def index
        @video = Video.paginate(page: params[:page], per_page: 3).order('created_at DESC')
        respond_to do |format|
            format.html
            format.json{ render json: @video }
        end
    end
    
    def player
        @view = Video.find(Integer(params[:id]))
        impressionist(@view,"messages")
        @view.views = @view.impressionist_count
        @view.save
        @play = Video.find(params[:id])
    end
    
    def like_toggle
        like = Likevideo.find_by(user_id: current_user.id, video_id: params[:video_id])
        if like.nil?
            Likevideo.create(user_id: current_user.id, video_id: params[:video_id])
        else
           like.destroy 
        end
        
        redirect_to :back
    end
    
    def comment
        Commentvideo.create(script: params[:comment], video_id: params[:video_id], user_id: params[:user_id], blind: false) 
        redirect_to :back
    end
end

app/helpers/video_helper.rb
module VideoHelper
    
end

app/views/video/index.html.erb
<style>
  strong{
      font-weight:bold;
      font-size:16pt;
      line-height:normal;
  }
  strong_sub{
      font-weight:bold;
      font-size:13pt;
      line-height:normal;
  }
  
  
</style>

<head>
  <nav>
    <div class="nav-wrapper red darken-1">
        <div class="col s2">
        </div>
        <div class="col s10">
            <a href="/blog/index" class="breadcrumb" style="padding-left:10px;"><strong_sub>영상</strong_sub></a>
        </div>
    </div>
  </nav>
</head>

<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>
<body>
  <% @video.each_with_index do |video,i| %>
    <a href="/video/player?id=<%=video.id%>">
      <div class="col s12 m7">
        <div class="card horizontal">
            <div class="card-image" style="width:38%;">
              <img src="http://img.youtube.com/vi/<%=video.videoid%>/1.jpg" style="width:100%;">
            </div>
            <div class="card-stacked">
                <div class="card-content">
                      <h6><strong><%=video.title%></strong></h6>
                </div>
                <div class="card-action">
                    <div style='width:190px; text-overflow:ellipsis; overflow:hidden; white-space:nowrap;'><nobr><%=video.subtitle%></nobr></div>
                </div>
            </div>
        </div>
      </div>
    </a>
  <% end %>
  
  <div class="row">
      <%= will_paginate(@video, :renderer => 'PaginationHelper::LinkRenderer') %>
  </div>
  <!--
    <ul class="pagination">
      <li class="left"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
      
      <li class="active"><a href="/video/index?page=1">1</a></li>
      <li class="waves-effect"><a href="/video/index?page=2">2</a></li>
      <li class="waves-effect"><a href="/video/index?page=3">3</a></li>
      <li class="waves-effect"><a href="/video/index?page=4">4</a></li>
      <li class="waves-effect"><a href="/video/index?page=5">5</a></li>
      
      <li class="right"><a href="/video/index?page=2"><i class="material-icons">chevron_right</i></a></li>
    </ul>
    -->
</body>

app/views/video/player.html.erb
<style>
  strong{
      font-weight:bold;
      font-size:16pt;
      line-height:normal;
  }
  strong_sub{
      font-weight:bold;
      font-size:13pt;
      line-height:normal;
  }
  #but_comment{
    float:right;
    height:100%;
    font-size:20px;
    line-height: 30px;
    vertical-align:middle;
  }
</style>

<head>
  <nav>
    <div class="nav-wrapper red darken-1">
        <div class="col s2">
        </div>
        <div class="col s10">
            <a href="/video/index" class="breadcrumb" style="padding-left:10px;"><strong_sub>영상</strong_sub></a>
        </div>
    </div>
  </nav>
</head>

<!-- 1. The <iframe> (and video player) will replace this <div> tag. -->
<body>
  <div class="row container">
    <div class="row" id="article_classification">
      <strong>
        <a style="color:red;">영상</a>
      </strong>
    </div>
    <div class="row" id="article_header">
      <h4><%=@play.title%></h4>
    </div>
    <div class="row" id="article_date">
      <h8><%=@play.created_at.strftime("%Y.%m.%d")%></h8><h8 style="float:right;"><%= @view.views %> views</h8>
    </div>
    <div class="row" id="article_subheader">
      <h6><strong><%=simple_format(@play.subtitle)%></strong></h6>
    </div>
  </div>
  
  <div class="video-container">
    <div id="player" style="width:100%;"></div>
  </div>
  
  <div class="row"></div>
  
  <ul class="collection">
    <li class="collection-item" style="background-color:#e9ecef;"><%= @play.likevideos.size %> 명이 좋아합니다.</li>
    
    <% if user_signed_in? %><!-- 관리자만의 탭 입력 -->
      <li class="collection-item" style="background-color:#e9ecef;">
        <% if current_user.is_like_video?(@play) %>
          <%= link_to "좋아요 취소", video_like_url(@play), method: "post" %>
        <% else %>
          <%= link_to "좋아요", video_like_url(@play), method: "post" %>
        <% end %>
      </li>
      <li class="collection-item">
        <%= form_tag '/video/comment' do %>
          <div class="row container">
            <strong_sub><a style="color:black;"><%=current_user.name%></a></strong_sub>
          </div>
          <div class="row container">
            <div class="input-field">
              <textarea id="icon_prefix2" class="materialize-textarea" type="text" name="comment" style="margin-bottom: 0px;"></textarea>
              <label for="icon_prefix2">댓글</label>
            </div>
            <input type="hidden" name="video_id" value="<%=@play.id%>">
            <input type="hidden" name="user_id" value="<%=current_user.id%>">
          </div>
          <div class="row container">
            <input class="waves-effect waves-light btn" id="but_comment" type="submit" value="작성">
          </div>
        <% end %>
      </li>
    <% end %>
    
    <% @play.commentvideos.each do |c| %>
      <li class="collection-item">
        <strong_sub>
          <a style="color:black;"><%= User.find(c.user_id).name %></a>
        </strong_sub>
        <br>
        <a style="color:black; padding-left:5pt;"><%=c.script %></a>
      </li>
    <% end %>
  </ul>

  <script>
    // 2. This code loads the IFrame Player API code asynchronously.
    var tag = document.createElement('script');

    tag.src = "https://www.youtube.com/iframe_api";
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    // 3. This function creates an <iframe> (and YouTube player)
    //    after the API code downloads.
    var player;
    function onYouTubeIframeAPIReady() {
      player = new YT.Player('player', {
        height: '300',
        width: '400',
        videoId: '<%=@play.videoid%>',
        events: {
          'onReady': onPlayerReady,
          //'onStateChange': onPlayerStateChange
        }
      });
    }  

    // 4. The API will call this function when the video player is ready.
    function onPlayerReady(event) {
      event.target.playVideo();
    }

    // 5. The API calls this function when the player's state changes.
    //    The function indicates that when playing a video (state=1),
    //    the player should play for six seconds and then stop.
    /*var done = false;
    function onPlayerStateChange(event) {
      if (event.data == YT.PlayerState.PLAYING && !done) {
        setTimeout(stopVideo, 6000);
        done = true;
      }
    }
    function stopVideo() {
      player.stopVideo();
    }*/
  </script>
</body>