config/routes.rb
Rails.application.routes.draw do
  
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :products, only: [:index]

  root 'main#index'
  post '/sendtest' => 'tm#sendtest'
  post '/send' => 'tm#trigger_sms_alerts'
  
  get '/admin' => 'admin#panel'
  get '/admin/prev_list' => 'admin#prev_list'
  get '/admin/session_list' => 'admin#session_list'     
  get '/admin/admin_list' => 'admin#admin_list'
  get '/admin/register' => 'admin#register'
  get '/admin/publicity' => 'admin#publicity'
  get '/admin/publicity_new' => 'admin#publicity_new'
  get '/admin/publicity/history' => 'admin#publicity_history'
  get '/admin/admin_enrollment' => 'admin#admin_enrollment'
  post '/admin/admin_enrollment/create' => 'admin#admin_enrollment_create'
  post '/admin/create' => 'admin#create'
  post '/admin/delete' => 'admin#delete'
  post '/admin/publicity_new/sendtext' => 'admin#sendtext_user'
  get '/admin/video' => 'admin#video'
  post '/admin/video/create' => 'admin#video_create'
  get '/admin/news' => 'admin@news'
  post '/admin/news/create' => 'admin#news_create'
  post '/admin/statistics/member/record' => 'admin#statistics_member_record'
  
  get '/video/index' => 'video#index'
  get '/video/player' => 'video#player'
  post '/video/comment' => 'video#comment'
  get '/news/index' => 'news#newsindex'
  get '/news/article' => 'news#article'
  get '/blog/index' => 'news#blogindex'
  post '/news/comment' => 'news#comment'
  get '/users/invitation' => 'users#invitation'
  post '/users/invitation/sendtext' => 'users#invitation_sendtext'
  
  get '/error' => 'sessions#error'
  
  get '/admin/statistics/member' => 'admin#statistics_member'
  get '/admin/statistics/post' => 'admin#statistics_post'
  
  resources :videos, except: [:show] do
    post "/like", to: "video#like_toggle"
  end
  resources :news, except: [:show] do
    post "/like", to: "news#like_toggle"
  end

end

app/models/news.rb
class News < ActiveRecord::Base
    is_impressionable
    
    has_many :likenews
    has_many :liked_users, through: :likenews, source: :user
    has_many :commentnews
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
   impressionist :actions=>[:article]
    
    def newsindex
        @news = News.paginate(page: params[:page], per_page: 3).order('created_at DESC')
        respond_to do |format|
            format.html
            format.json{ render json: @news }
        end
    end
    
    def article
        @article = News.find(params[:id])
        @view = News.find(Integer(params[:id]))
        impressionist(@view,"messages")
        @view.views = @view.impressionist_count
        @view.save
    end
    
    def like_toggle
        like = Likenews.find_by(user_id: current_user.id, news_id: params[:news_id])
        if like.nil?
            Likenews.create(user_id: current_user.id, news_id: params[:news_id])
        else
           like.destroy 
        end
        
        redirect_to :back
    end
    
    def comment
        Commentnews.create(script: params[:comment], news_id: params[:video_id], user_id: params[:user_id], blind: false) 
        redirect_to :back
    end
    
    def blogindex
        @titles = Array.new
        @subtitles = Array.new
        @mainview = Array.new
        @created = Array.new
        @img = Array.new
        
        require 'open-uri'
        doc = Nokogiri::HTML(open("http://blog.naver.com/PostList.nhn?from=postList&blogId=sulhoon21&currentPage=1"),nil,'euc-kr')
        @titles << doc.css('.htitle').css('span')[0].text
        @subtitles << doc.css('.view').css('p')[0].text
        @mainview << doc.css('.view').css('p')[1].text
        @created << doc.css('.p12').css('p')[0].text
        #doc = doc.css('._photoImage').css('img')[0]
        #if doc['src'] != nil
        #    doc = doc['src']
        #end
        #@img << doc
        doc = Nokogiri::HTML(open("http://blog.naver.com/PostList.nhn?from=postList&blogId=sulhoon21&currentPage=2"),nil,'euc-kr')
        @titles << doc.css('.htitle').css('span')[0].text
        @subtitles << doc.css('.view').css('p')[0].text
        @mainview << doc.css('.view').css('p')[1].text
        @created << doc.css('.p12').css('p')[0].text
        doc = doc.css('._photoImage').css('img')[0]
        if doc['src'] != nil
            doc = doc['src']
        end
        @img << doc
        doc = Nokogiri::HTML(open("http://blog.naver.com/PostList.nhn?from=postList&blogId=sulhoon21&currentPage=3"),nil,'euc-kr')
        @titles << doc.css('.htitle').css('span')[0].text
        @subtitles << doc.css('.view').css('p')[0].text
        @mainview << doc.css('.view').css('p')[1].text
        @created << doc.css('.p12').css('p')[0].text
        doc = Nokogiri::HTML(open("http://blog.naver.com/PostList.nhn?from=postList&blogId=sulhoon21&currentPage=4"),nil,'euc-kr')
        @titles << doc.css('.htitle').css('span')[0].text
        @subtitles << doc.css('.view').css('p')[0].text
        @mainview << doc.css('.view').css('p')[1].text
        @created << doc.css('.p12').css('p')[0].text
        doc = Nokogiri::HTML(open("http://blog.naver.com/PostList.nhn?from=postList&blogId=sulhoon21&currentPage=5"),nil,'euc-kr')
        @titles << doc.css('.htitle').css('span')[0].text
        @subtitles << doc.css('.view').css('p')[0].text
        @mainview << doc.css('.view').css('p')[1].text
        @created << doc.css('.p12').css('p')[0].text
        doc = Nokogiri::HTML(open("http://blog.naver.com/PostList.nhn?from=postList&blogId=sulhoon21&currentPage=6"),nil,'euc-kr')
        @titles << doc.css('.htitle').css('span')[0].text
        @subtitles << doc.css('.view').css('p')[0].text
        @mainview << doc.css('.view').css('p')[1].text
        @created << doc.css('.p12').css('p')[0].text
        doc = Nokogiri::HTML(open("http://blog.naver.com/PostList.nhn?from=postList&blogId=sulhoon21&currentPage=7"),nil,'euc-kr')
        @titles << doc.css('.htitle').css('span')[0].text
        @subtitles << doc.css('.view').css('p')[0].text
        @mainview << doc.css('.view').css('p')[1].text
        @created << doc.css('.p12').css('p')[0].text
        doc = Nokogiri::HTML(open("http://blog.naver.com/PostList.nhn?from=postList&blogId=sulhoon21&currentPage=8"),nil,'euc-kr')
        @titles << doc.css('.htitle').css('span')[0].text
        @subtitles << doc.css('.view').css('p')[0].text
        @mainview << doc.css('.view').css('p')[1].text
        @created << doc.css('.p12').css('p')[0].text
        doc = Nokogiri::HTML(open("http://blog.naver.com/PostList.nhn?from=postList&blogId=sulhoon21&currentPage=9"),nil,'euc-kr')
        @titles << doc.css('.htitle').css('span')[0].text
        @subtitles << doc.css('.view').css('p')[0].text
        @mainview << doc.css('.view').css('p')[1].text
        @created << doc.css('.p12').css('p')[0].text
        doc = Nokogiri::HTML(open("http://blog.naver.com/PostList.nhn?from=postList&blogId=sulhoon21&currentPage=10"),nil,'euc-kr')
        @titles << doc.css('.htitle').css('span')[0].text
        @subtitles << doc.css('.view').css('p')[0].text
        @mainview << doc.css('.view').css('p')[1].text
        @created << doc.css('.p12').css('p')[0].text
        #doc.css('div#title_1 span')[0].each do |location|
        #    @titles << location
        #end
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/article.html.erb
<style>
  strong{
      font-weight:bold;
      font-size:16pt;
      line-height:normal;
  }
  strong_sub{
      font-weight:bold;
      font-size:13pt;
      line-height:normal;
  }
  img{
      width:70%;
  }
  #but_comment{
    float:right;
    height:100%;
    font-size:20px;
    line-height: 30px;
    vertical-align:middle;
  }
</style>

<head>
  <nav>
    <div class="nav-wrapper blue accent-3">
        <div class="col s2">
        </div>
        <div class="col s10">
            <a href="/news/index" class="breadcrumb" style="padding-left:10px;"><strong_sub>언론활동</strong_sub></a>
        </div>
    </div>
  </nav>
</head>

<body>
  <div class="row container">
    <div class="row" id="article_classification">
      <strong>
        <a style="color:blue;">기사</a>
      </strong>
    </div>
    <div class="row" id="article_header">
      <h4><%=@article.title%></h4>
    </div>
    <div class="row" id="article_date">
      <h8><%=@article.posted.strftime("%Y.%m.%d")%></h8><h8 style="float:right;"><%= @view.views %> views</h8>
    </div>
    <div class="row" id="article_subheader">
      <h6><strong><%=simple_format(@article.subtitle)%></strong></h6>
    </div>
    <div class="row" id="article_img">
        <img src="<%=@article.imgurl%>">
    </div>
    <div class="row" id="article_script">
        <%=simple_format(@article.script)%>
    </div>
  </div>
  
  <div class="row"></div>
  
  <ul class="collection">
    <li class="collection-item" style="background-color:#e9ecef;"><%= @article.likenews.size %> 명이 좋아합니다.</li>
    
    <% if user_signed_in? %><!-- 관리자만의 탭 입력 -->
      <% if current_user.is_like_news?(@article) %>
        <%= link_to "좋아요 취소", news_like_url(@article), method: "post" %>
      <% else %>
        <%= link_to "좋아요", news_like_url(@article), method: "post" %>
      <% end %>
      </li>
      <li class="collection-item">
        <%= form_tag '/news/comment' do %>
          <div class="row container">
            <strong_sub><a style="color:black;"><%=current_user.name%></a></strong_sub>
          </div>
          <div class="row container">
            <div class="input-field">
              <textarea id="icon_prefix2" class="materialize-textarea" type="text" name="comment" style="margin-bottom: 0px;"></textarea>
              <label for="icon_prefix2">댓글</label>
            </div>
            <input type="hidden" name="video_id" value="<%=@article.id%>">
            <input type="hidden" name="user_id" value="<%=current_user.id%>">
          </div>
          <div class="row container">
            <input class="waves-effect waves-light btn" id="but_comment" type="submit" value="작성">
          </div>
        <% end %>
      </li>
    <% end %>
    
    <% @article.commentnews.each do |c| %>
      <li class="collection-item">
        <strong_sub>
          <a style="color:black;"><%= User.find(c.user_id).name %></a>
        </strong_sub>
        <br>
        <a style="color:black; padding-left:5pt;"><%=c.script %></a>
      </li>
    <% end %>
  </ul>
</body>

app/views/news/blogindex.html.erb
<style>
    strong{
        font-weight:bold;
        font-size:16pt;
        line-height:normal;
    }
    strong_sub{
        font-weight:bold;
        font-size:13pt;
        line-height:normal;
    }
</style>

<head>
  <nav>
    <div class="nav-wrapper green">
        <div class="col s2">
        </div>
        <div class="col s10">
            <a href="/blog/index" class="breadcrumb" style="padding-left:10px;"><strong_sub>블로그</strong_sub></a>
        </div>
    </div>
  </nav>
</head>

<body>
    <% @titles.each_with_index do |blog,i| %>
        <a href="http://blog.naver.com/PostList.nhn?from=postList&blogId=sulhoon21&currentPage=<%=i%>">
          <div class="col s12 m7">
            <div class="card horizontal" style="color:black;">
                <div class="card-image" style="width:38%;">
                  <img src="<%=@img[0]%>" style="width:100%;">
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <h6><strong><%=blog%></strong></h6>
                    </div>
                    <div class="card-action">
                        <div style='width:190px; text-overflow:ellipsis; overflow:hidden; white-space:nowrap;'><nobr><%=@subtitles[i]%></nobr></div>
                    </div>
                </div>
            </div>
          </div>
        </a>
    <% end %>
</body>

app/views/news/index.html.erb
<p><%=@titles%></p>
<p><%=@subtitles%></p>
<p><%=@mainview%></p>
<p><%=@img%></p>

<% @titles.each_with_index do |blog,i| %>
    <div class="col s12 m7">
        <div class="card horizontal">
            <div class="card-image">
                <img src="<%=@img[i]%>">
            </div>
            <div class="card-stacked">
                <div class="card-content">
                    <h5><%=blog%></h5>
                    <p><%=@subtitles[i]%></p>
                    <p><%=@mainview[i]%></p>
                </div>
                <div class="card-action">
                    <a href="http://www.naver.com">기사 보러가기</a>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/news/newsindex.html.erb
<style>
    strong{
        font-weight:bold;
        font-size:16pt;
        line-height:normal;
    }
    strong_sub{
        font-weight:bold;
        font-size:13pt;
        line-height:normal;
    }
</style>

<head>
  <nav>
    <div class="nav-wrapper blue accent-3">
        <div class="col s2">
        </div>
        <div class="col s10">
            <a href="/blog/index" class="breadcrumb" style="padding-left:10px;"><strong_sub>언론활동</strong_sub></a>
        </div>
    </div>
  </nav>
</head>

<body>
    <% @news.each_with_index do |news,i| %>
        <a href="/news/article?id=<%=news.id%>">
          <div class="col s12 m7">
            <div class="card horizontal" style="color:black;">
                <div class="card-image" style="width:38%;">
                  <img src="<%=news.imgurl%>" style="width:100%;">
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <h6><strong><%=news.title%></strong></h6>
                    </div>
                    <div class="card-action">
                        <div style='width:190px; text-overflow:ellipsis; overflow:hidden; white-space:nowrap;'><nobr><%=news.subtitle%></nobr></div>
                    </div>
                </div>
            </div>
          </div>
        </a>
    <% end %>
     
    <div class="row">
        <%= will_paginate(@news, :renderer => 'PaginationHelper::LinkRenderer') %>
    </div>
</body>