config/routes.rb
Rails.application.routes.draw do
  
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :products, only: [:index]

  root 'main#index'
  post '/sendtest' => 'tm#sendtest'
  post '/send' => 'tm#trigger_sms_alerts'
  
  get '/admin' => 'admin#panel'
  get '/admin/prev_list' => 'admin#prev_list'
  get '/admin/session_list' => 'admin#session_list'     
  get '/admin/admin_list' => 'admin#admin_list'
  get '/admin/register' => 'admin#register'
  get '/admin/publicity' => 'admin#publicity'
  get '/admin/publicity_new' => 'admin#publicity_new'
  get '/admin/publicity/history' => 'admin#publicity_history'
  get '/admin/admin_enrollment' => 'admin#admin_enrollment'
  post '/admin/admin_enrollment/create' => 'admin#admin_enrollment_create'
  post '/admin/create' => 'admin#create'
  post '/admin/delete' => 'admin#delete'
  post '/admin/publicity_new/sendtext' => 'admin#sendtext_user'
  get '/admin/video' => 'admin#video'
  post '/admin/video/create' => 'admin#video_create'
  get '/admin/news' => 'admin@news'
  post '/admin/news/create' => 'admin#news_create'
  post '/admin/statistics/member/record' => 'admin#statistics_member_record'
  
  get '/video/index' => 'video#index'
  get '/video/player' => 'video#player'
  post '/video/comment' => 'video#comment'
  get '/news/index' => 'news#newsindex'
  get '/news/article' => 'news#article'
  get '/blog/index' => 'news#blogindex'
  post '/news/comment' => 'news#comment'
  get '/users/invitation' => 'users#invitation'
  post '/users/invitation/sendtext' => 'users#invitation_sendtext'
  
  get '/error' => 'sessions#error'
  
  get '/admin/statistics/member' => 'admin#statistics_member'
  get '/admin/statistics/post' => 'admin#statistics_post'
  
  resources :videos, except: [:show] do
    post "/like", to: "video#like_toggle"
  end
  resources :news, except: [:show] do
    post "/like", to: "news#like_toggle"
  end

end

app/models/commentnews.rb
class Commentnews < ActiveRecord::Base
    belongs_to :news
end

app/models/commentvideo.rb
class Commentvideo < ActiveRecord::Base
    belongs_to :video
end

app/models/history_text.rb
class HistoryText < ActiveRecord::Base
end

app/models/likenews.rb
class Likenews < ActiveRecord::Base
    belongs_to :user
    belongs_to :news
end

app/models/likevideo.rb
class Likevideo < ActiveRecord::Base
    belongs_to :user
    belongs_to :video
end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
    is_impressionable
    
    has_many :likenews
    has_many :liked_users, through: :likenews, source: :user
    has_many :commentnews
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    
    has_many :likevideos
    has_many :liked_videos, through: :likevideos, source: :video
    
    def is_like_video?(video)
        Likevideo.find_by(user_id: self.id, video_id: video.id).present?
    end
    
    def is_like_news?(news)
        Likenews.find_by(user_id: self.id, news_id: news.id).present?
    end
end

app/models/video.rb
class Video < ActiveRecord::Base
    is_impressionable
    
    has_many :likevideos
    has_many :liked_users, through: :likevideos, source: :user
    has_many :commentvideos
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

app/controllers/tm_controller.rb
class TmController < ApplicationController
  before_action :authenticate#, only: [:sendtest]
  before_action :authenticate_admin#, only: [:sendtest]
  
  def sendtest
    accountSID = ENV['TWILIO_SID']
    authToken = ENV['TWILIO_AUTH']
    @client = Twilio::REST::Client.new accountSID, authToken #Rails.application.secrets.twilio_account_sid, Rails.application.secrets.twilio_auth_token  
    from = ENV['BASE_NUM']
    friends = {'+821065101264' => "HBK"}
    
    #frineds.each do |key, value| 
      message = @client.account.messages.create(
        :from=> from,
        :to=> '+821065101264',
        :body=> "Hi"
      )
      puts "Sent message" 
    #end
    
    redirect_to '/'
  end
#    skip_before_action :verify_authenticity_token
 # rescue_from StandardError do |exception|
  #  trigger_sms_alerts(exception)
  #end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/enroll_helper.rb
module EnrollHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pagination_helper.rb
module PaginationHelper
    class LinkRenderer < WillPaginate::ActionView::LinkRenderer
    protected
        
        def page_number(page)
            unless page == current_page
              link(page, page, :rel => rel_value(page))
            else
              link(page, "#", :class => 'active')
            end
        end
    
        def gap
            text = @template.will_paginate_translate(:page_gap) { '&hellip;' }
            %(<li class="disabled"><a>#{text}</a></li>)
        end
    
        def next_page
            num = @collection.current_page < @collection.total_pages && @collection.current_page + 1
            previous_or_next_page(num, @options[:next_label], 'next')
        end
    
        def previous_or_next_page(page, text, classname)
            if page
              link(text, page, :class => classname)
            else
              link(text, "#", :class => classname + ' disabled')
            end
        end
    
        def html_container(html)
            tag(:div, tag(:ul, html), container_attributes)
        end
    
    private
    
        def link(text, target, attributes = {})
            if target.is_a? Fixnum
              attributes[:rel] = rel_value(target)
              target = url(target)
            end
    
            unless target == "#"
                attributes[:href] = target
            end
    
            classname = attributes[:class]
            attributes.delete(:classname)
            tag(:li, tag(:a, text, attributes), :class => classname)
            end
        end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def log_out
       session.delete(:user_id) # session[:user_id]=nil
       @current_user = nil
    end
    
    def current_user
       if @current_user.nil?
           @current_user = User.find_by(id: session[:user_id])
       end
       return @current_user
    end
    
    def user_signed_in?
       !current_user.nil?   # same as return # session[:user_id]
    end
    
end

app/helpers/tm_helper.rb
module TmHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/video_helper.rb
module VideoHelper
    
end

app/views/admin/admin_enrollment.html.erb
<head>
  <nav>
    <div class="nav-wrapper cyan darken-1">
      <div class="col s12">
        <a href="#!" class="breadcrumb" style="padding-left:10px;">Sudo</a>
        <a href="/admin" class="breadcrumb">AdminPanel</a>
        <a href="/admin/admin_enrollment" class="breadcrumb">AdminEnrollment</a>
      </div>
    </div>
  </nav>
</head>

<%= form_tag '/admin/admin_enrollment/create', method: 'post' do %>
    <p>이메일</p><input type="text" name="email"><br>
    <input type="submit">
<% end %>

app/views/admin/admin_list.html.erb
<head>
  <nav>
    <div class="nav-wrapper cyan darken-1">
      <div class="col s12">
        <a href="#!" class="breadcrumb" style="padding-left:10px;">Sudo</a>
        <a href="/admin" class="breadcrumb">AdminPanel</a>
        <a href="/admin/admin_list" class="breadcrumb">AdminList</a>
      </div>
    </div>
  </nav>
</head>

<table border="1" summary="리스트">
    <caption>리스트</caption>
    <thead>
        <tr>
            <th scope="col">이름</th>
            <th scope="col">직책</th>
            <th scope="col">전화번호</th>
            <th scope="col">이메일</th>
            <th scope="col">Status</th>
            <th scope="col">관리자 삭제</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td colspan="4">hbk</td>
        </tr>
    </tfoot>
    <tbody>
        <% @member.each do |member| %>
            <tr>
                <th scope="row"><%= member.name %></th>
                <td><%= member.job %></td>
                <td><%= member.phone %></td>
                <td><%= member.email %></td>
                <td><%= member.admin %></td>
                <td>
                    <%= form_tag '/admin/delete', method: 'post' do %>
                        <input type="hidden" value="<%= member.id %>" name="uid">
                        <input type="submit" value="삭제">
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/admin/news.html.erb
<style>
  #but_sign{
      width:100%;
      height:50px;
      font-size:30px;
      vertical-align:middle;
  }
</style>

<head>
  <nav>
    <div class="nav-wrapper cyan darken-1">
      <div class="col s12">
        <a href="#!" class="breadcrumb" style="padding-left:10px;">Sudo</a>
        <a href="/admin" class="breadcrumb">AdminPanel</a>
        <a href="/admin/news" class="breadcrumb">News</a>
      </div>
    </div>
  </nav>
</head>

<script>
  $(document).ready(function() {
    $('select').material_select();
  });
</script>

<%= form_tag '/admin/news/create', method: 'post' do %>
  <div class="row container">
    <div class="input-field">
      <input placeholder="뉴스 제목" id="first_name" type="text" class="validate" name="title">
      <label for="TITLE">뉴스 제목</label>
    </div>
  </div>
  <div class="row container">
    <div class="input-field">
      <input placeholder="뉴스 부제목" id="first_name" type="text" class="validate" name="subtitle">
      <label for="SUBTITLE">뉴스 부제목</label>
    </div>
  </div>
  <div class="row container">
    <div class="input-field">
      <i class="material-icons prefix">mode_edit</i>
      <textarea id="icon_prefix2" class="materialize-textarea" type="text" name="script"></textarea>
      <label for="icon_prefix2">기사 내용</label>
    </div>
  </div>
  <div class="row container">
    <div class="input-field">
      <input placeholder="POSTED_DATE" type="date" class="datepicker" name="posted">
      <label for="POSTED_DATE">POSTED_DATE</label>
    </div>
  </div>
  <div class="row container">
    <div class="input-field">
      <input placeholder="이미지 URL" id="first_name" type="text" class="validate" name="imgurl">
      <label for="IMAGE_URL">이미지 URL</label>
    </div>
  </div>
        
  <input type="hidden" name="publisher" value="<%=current_user.id%>">
  
  <div class="row container">
      <input class="waves-effect waves-light btn" id="but_sign" type="submit" value="뉴스 등록">
  </div>
<% end %>
<script>
    $('.datepicker').pickadate({
        selectMonths: true, // Creates a dropdown to control month
        selectYears: 15 // Creates a dropdown of 15 years to control year
    });
</script>

app/views/admin/panel.html.erb
<head>
  <nav>
    <div class="nav-wrapper cyan darken-1">
      <div class="col s12">
        <a href="#!" class="breadcrumb" style="padding-left:10px;">Sudo</a>
        <a href="/admin" class="breadcrumb">AdminPanel</a>
      </div>
    </div>
  </nav>
</head>

<style>
    .btn-shitlarge{
        width: 200px;
        height: 200px;
    }
    #panel{
        text-align:center;
    }
    #make_black{
        color: black;
    }
    #header_pad{
        padding-left:20px;
    }
</style>

<body>
    <div class="row container">
        <div class="col s6">
            <ul class="collection">
                <li class="collection-header" id="header_pad"><h4>기존 DB</h4></li>
                <li class="collection-item"></li>
                
                <a class="collection-item avatar" id="make_black" href="/admin/prev_list">
                  <i class="material-icons circle blue">contacts</i>
                  <span class="title">기존 DB 조회</span>
                  
                  <p>총 <%=@mem%>명
                  </p>
                </a>
                
                <a class="collection-item avatar" id="make_black" href="/admin/register">
                  <i class="material-icons circle green">playlist_add</i>
                  <span class="title">기존 DB 등록</span>
                  
                  <p>관리 DB 등록
                  </p>
                </a>
                
                <a class="collection-item avatar" id="make_black" href="/admin/publicity">
                  <i class="material-icons circle red">cloud</i>
                  <span class="title">기존 DB 홍보</span>
                  
                  <p>기존 DB 문자, 카카오톡 전송
                  </p>
                </a>
                
                <a class="collection-item avatar" id="make_black" href="/admin/statistics/member">
                  <i class="material-icons circle">insert_chart</i>
                  <span class="title">기존 DB 분석</span>
                  
                  <p>기존 DB 통계
                  </p>
                </a>
            </ul>
        </div>
    
        <div class="col s6">
            <ul class="collection">
                <li class="collection-header" id="header_pad"><h4>가입자</h4></li>
                <li class="collection-item"></li>
                
                <a class="collection-item avatar" id="make_black" href="/admin/session_list">
                  <i class="material-icons circle blue">stars</i>
                  <span class="title">가입자 현황</span>
                  
                  <p>총 <%=@usr%>명
                  </p>
                </a>
                
                <a class="collection-item avatar" id="make_black" href="/admin/publicity_new">
                  <i class="material-icons circle green">cloud</i>
                  <span class="title">가입자 홍보</span>
                  
                  <p>가입자 문자, 카카오톡 전송
                  </p>
                </a>
                
                <a class="collection-item avatar" id="make_black" href="/admin/publicity">
                  <i class="material-icons circle red">assignment_ind</i>
                  <span class="title">지인초대 현황</span>
                  
                  <p>지인 초대 DB 조회
                  </p>
                </a>
                
                <a class="collection-item avatar" id="make_black" href="/admin/publicity/history">
                  <i class="material-icons circle">assignment_ind</i>
                  <span class="title">가입자 홍보 기록</span>
                  
                  <p>총 <%=@pub%>건
                  </p>
                </a>
            </ul>
        </div>
    </div>
    
    <div class="row container">
        <div class="col s6">
            <ul class="collection">
                <li class="collection-header" id="header_pad"><h4>게시물 관리</h4></li>
                <li class="collection-item"></li>
                
                <a class="collection-item avatar" id="make_black" href="/admin/video">
                  <i class="material-icons circle blue">cloud</i>
                  <span class="title">영상 등록</span>
                  
                  <p>총 <%=@vid%>건
                  </p>
                </a>
                
                <a class="collection-item avatar" id="make_black" href="/admin/news">
                  <i class="material-icons circle green">stars</i>
                  <span class="title">뉴스 등록</span>
                  
                  <p>총 <%=@new%>건
                  </p>
                </a>
                
                <a class="collection-item avatar" id="make_black" href="/admin/statistics/post">
                  <i class="material-icons circle red">insert_chart</i>
                  <span class="title">게시물 분석</span>
                  
                  <p>게시물 DB 통계
                  </p>
                </a>
            </ul>
        </div>
    
        <div class="col s6">
            <ul class="collection">
                <li class="collection-header" id="header_pad"><h4>관리자</h4></li>
                <li class="collection-item"></li>
                
                <a class="collection-item avatar" id="make_black" href="/admin/admin_list">
                  <i class="material-icons circle blue">cloud</i>
                  <span class="title">관리자 현황</span>
                  
                  <p>총 <%=@adm%>명
                  </p>
                </a>
                
                <a class="collection-item avatar" id="make_black" href="/admin/admin_enrollment">
                  <i class="material-icons circle green">stars</i>
                  <span class="title">관리자 등록</span>
                  
                  <p>이메일 주소로 등록
                  </p>
                </a>
            </ul>
        </div>
    </div>
</body>

app/views/admin/prev_list.html.erb
<head>
  <nav>
    <div class="nav-wrapper cyan darken-1">
      <div class="col s12">
        <a href="#!" class="breadcrumb" style="padding-left:10px;">Sudo</a>
        <a href="/admin" class="breadcrumb">AdminPanel</a>
        <a href="/admin/prev_list" class="breadcrumb">PrevList</a>
      </div>
    </div>
  </nav>
</head>

<body>
        <table border="1" summary="리스트">
            <caption>리스트</caption>
            <thead>
                <tr>
                    <th scope="col">이름</th>
                    <th scope="col">휴대폰</th>
                    <th scope="col">거주동</th>
                    <th scope="col">선거구</th>
                    <th scope="col">지지분류</th>
                    <th scope="col">연령대</th>
                    <th scope="col">성별</th>
                    <th scope="col">인지도</th>
                    <th scope="col">의정평가</th>
                    <th scope="col">재지지 의향</th>
                    <th scope="col">국정지지도</th>
                    <th scope="col">정당지지도</th>
                    <th scope="col">경기지사</th>
                    <th scope="col">직업</th>
                    <th scope="col">직책</th>
                    <th scope="col">일반번호</th>
                    <th scope="col">직장번호</th>
                    <th scope="col">이메일</th>
                    <th scope="col">추천인</th>
                    <th scope="col">출신지역</th>
                    <th scope="col">생년월일</th>
                    <th scope="col">당비당원분류</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td colspan="4">hbk</td>
                </tr>
            </tfoot>
            <tbody>
                <% @member.each do |member| %>
                    <tr>
                        <th scope="row"><%= member.name %></th>
                        <td><%= member.phone %></td>
                        <% if member.residence==1 %>
                            <td>상동</td>
                        <% elsif member.residence==2 %>
                            <td>상 1동</td>
                        <% elsif member.residence==3 %>
                            <td>상 2동</td>
                        <% elsif member.residence==4 %>
                            <td>상 3동</td>
                        <% elsif member.residence==5 %>
                            <td>중동</td>
                        <% elsif member.residence==6 %>
                            <td>중 1동</td>
                        <% elsif member.residence==7 %>
                            <td>중 2동</td>
                        <% elsif member.residence==8 %>
                            <td>중 3동</td>
                        <% elsif member.residence==9 %>
                            <td>중 4동</td>
                        <% elsif member.residence==10 %>
                            <td>약대동</td>
                        <% else %>
                            <td> </td>
                        <% end %>
                        
                        <% if member.elec_constit==1 %>
                            <td>원미(을)</td>
                        <% elsif member.elec_constit==2 %>
                            <td>원미(갑)</td>
                        <% elsif member.elec_constit==3 %>
                            <td>오정</td>
                        <% elsif member.elec_constit==4 %>
                            <td>소사</td>
                        <% else %>
                            <td> </td>
                        <% end %>
                        
                        <% if member.support_ide <= 33 %>
                            <td>진보</td>
                        <% elsif member.support_ide > 33 && member.support_ide <63 %>
                            <td>중도</td>
                        <% elsif member.support_ide >= 63 %>
                            <td>보수</td>
                        <% else %>
                            <td> </td>
                        <% end %>
                        
                        <td><%= member.age %></td>
                        
                        <% if member.sex==1 %>
                            <td>남</td>
                        <% elsif member.sex==2 %>
                            <td>여</td>
                        <% else %>
                            <td> </td>
                        <% end %>
                        
                        <% if member.recog==1 %>
                            <td>안다</td>
                        <% elsif member.recog==2 %>
                            <td>모른다</td>
                        <% else %>
                            <td> </td>
                        <% end %>
                        
                        
                        <% if member.par_eval==1 %>
                            <td>잘한다</td>
                        <% elsif member.par_eval==2 %>
                            <td>보통</td>
                        <% elsif member.par_eval==3 %>
                            <td>못한다</td>
                        <% else %>
                            <td> </td>
                        <% end %>
                        
                        <% if member.support_re==1 %>
                            <td>있다</td>
                        <% elsif member.support_re==2 %>
                            <td>고민</td>
                        <% elsif member.support_re==3 %>
                            <td>없다</td>
                        <% else %>
                            <td> </td>
                        <% end %>
                        
                        <% if member.support_gov==1 %>
                            <td>잘한다</td>
                        <% elsif member.support_gov==2 %>
                            <td>보통</td>
                        <% elsif member.support_gov==3 %>
                            <td>못한다</td>
                        <% else %>
                            <td> </td>
                        <% end %>
                        
                        <% if member.support_party==1 %>
                            <td>더민주</td>
                        <% elsif member.support_party==2 %>
                            <td>자유</td>
                        <% elsif member.support_party==3 %>
                            <td>국민</td>
                        <% elsif member.support_party==4 %>
                            <td>바른</td>
                        <% elsif member.support_party==5 %>
                            <td>정의</td>
                        <% elsif member.support_party==6 %>
                            <td>무당</td>
                        <% else %>
                            <td> </td>
                        <% end %>
                            
                        <% if member.governer==1 %>
                            <td>남경필</td>
                        <% elsif member.governer==2 %>
                            <td>김진표</td>
                        <% else %>
                            <td> </td>
                        <% end %>
                        
                        <td><%= member.job %></td>
                        <td><%= member.position %></td>
                        <td><%= member.homenum %></td>
                        <td><%= member.compnum %></td>
                        <td><%= member.email %></td>
                        <td><%= member.recommender %></td>
                        <td><%= member.native %></td>
                        <td><%= member.birth %></td>
                        
                        <% if member.partyfee==1 %>
                            <td>O</td>
                        <% elsif member.partyfee==2 %>
                            <td>X</td>
                        <% else %>
                            <td> </td>
                        <% end %>
                        
                    </tr>
                <% end %>
            </tbody>
        </table>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <style>
    body {
      display: flex;
      min-height: 100vh;
      flex-direction: column;
    }
  
    main {
      flex: 1 0 auto;
    }
    
    head, body {
        font-family: "Nanum Gothic", sans-serif;
    }
    
  </style>
    
  <head>
    <title>국회의원 설훈</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    
    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    
    

    <script src="//ajax.googleapis.com/ajax/libs/webfont/1.4.10/webfont.js"></script>
    <script type="text/javascript">
      WebFont.load({
    
        // For google fonts
        google: {
          families: ['Droid Sans', 'Droid Serif']
        }
        // For early access or custom font
        custom: {
            families: ['Nanum Gothic'],
            urls: ['http://fonts.googleapis.com/earlyaccess/nanumgothic.css']
        }
    
      });
    </script>
  
    <!-- NAV AND SIDENAV -->
    <!-- NAV -->
    <nav class="indigo darken-1">
      <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>
      <div class="nav-wrapper">
        <a href="/" class="brand-logo center"><img src="/icon_main.png" style="width: 50px; padding-top: 3px;"></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <% if user_signed_in? %><!-- 관리자만의 탭 입력 -->
            <% if current_user.admin %>
              <li><a href=""><%= current_user.name %> <%= current_user.job %> 님</a></li>
              <li><%= link_to 'Admin', admin_path %></li>
            <% else %>
              <li><a href=""><%= current_user.name %> 님</a></li>
            <% end %>
            <li class="item"><%= link_to 'Sign Out', session_path(current_user), method: 'delete' %></li>  <!--     session DELETE /sessions/:id(.:format) sessions#destroy -->
          <% else %>
            <li class="item"><%= link_to 'Sign In', new_session_path %></li>
            <li class="item"><%= link_to 'Sign Up', new_user_path %></li>
          <% end %>
          
          <li><a href="">sass <span class="new badge">4</span></a></li>
          <li><a href="">sass</a></li>
        </ul>
      </div>
    </nav>
      
    <!-- side NAV -->
    <ul id="slide-out" class="side-nav">
      <% if user_signed_in? %><!-- 관리자만의 탭 입력 -->
        <% if current_user.admin %>
          <li><div class="userView"><img src="/bg_02.png" style="width:100%;">
            <a href="/admin"><img class="circle" src="/img_admin.png"></a>
            <a href="#!name"><span class="black-text name"><%= current_user.name %> <%= current_user.job %> 님</span></a>
            <a href="#!email"><span class="black-text email"><%= current_user.email %></span></a>
          </div></li>
        <% else %>
          <li><div class="userView"><img src="/bg_02.png" style="width:100%;">
            <a href="#!user"><img class="circle" src="/img_user.png"></a>
            <a href="#!name"><span class="black-text name"><%= current_user.name %> 님</span></a>
            <a href="#!email"><span class="black-text email"><%= current_user.email %></span></a>
          </div></li>
        <% end %>
        <li><div class="divider"></div></li>
        <li class="item"><%= link_to '로그아웃', session_path(current_user), method: 'delete' %></li>  <!--     session DELETE /sessions/:id(.:format) sessions#destroy -->
      <% else %>
        <li><div class="userView">
              <img src="/bg_02.png" style="width:100%;">
          </div>
        </li>
        <!--
        <li class="item"></%= link_to '로그인', new_session_path %></li>
        <li class="item"></%= link_to '회원가입', new_user_path %></li>
        -->
        <l><a class="waves-effect" href="/sessions/new">로그인</a></li>
        <l><a class="waves-effect" href="/users/new">회원가입</a></li>
      <% end %>
      
      <% if user_signed_in? && current_user.admin %>
        <li><a class="waves-effect" href="/admin"><i class="material-icons">cloud</i>Admin</a></li>
      <% end %>
      <li><div class="divider"></div></li>
      
      <li><a class="subheader">Subheader</a></li>
      <li><a class="waves-effect" href="#!">Third Link With Waves</a></li>
      <div class="chip" href="<%=ENV['DEV_ID']%>">
        <img src="<%=ENV['DEV_IMG']%>" alt="Contact Person">
        Han-Byul Kim
      </div>
    </ul>
    
    <script>
      // Initialize collapse button
      $(".button-collapse").sideNav();
      // Initialize collapsible (uncomment the line below if you use the dropdown variation)
      //$('.collapsible').collapsible();
    </script>
  </head>
  
  <body>
    <header>
      
    </header>
    
    <main>
      <%= yield %>
      <div class="progress">
          <div class="indeterminate"></div>
      </div>
      
      <script>
        $( document ).ready(function() {
          // hide spinner
          $(".progress").hide();
          // show spinner on AJAX start
          $(document).ajaxStart(function(){
            $(".progress").show();
          });
          // hide spinner on AJAX stop
          $(document).ajaxStop(function(){
            $(".progress").delay(3000).hide(0);
          });
        });
      </script>
    </main>
    
    <footer class="page-footer indigo darken-1">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">국회의원 설훈</h5>
            <p class="grey-text text-lighten-4">더불어 민주당</p>
          </div>
          <!--<div class="col l4 offset-l2 s12">
            <h5 class="white-text">Links</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
            </ul>
          </div>-->
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        <a class="grey-text text-lighten-4 left" href="<%=ENV['DEV_ID']%>">© 2017 Copyright Han-Byul Kim</a>
        <a class="grey-text text-lighten-4 right" href="<%=ENV['DEV_ID']%>"> | honor for DECENT 5th</a>
        </div>
      </div>
    </footer>
  </body>
  

    
</html>